---
- name: Expel instance from topology
  cartridge_expel_instance:
    alias: '{{ inventory_hostname }}'
    control_sock: '{{ cartridge_app_name | get_instance_control_sock(control_host) }}'
  delegate_to: '{{ control_host }}'
  tags: cartridge-replicasets

- name: Stop and disable systemd service
  systemd:
    name: '{{ instance_systemd_service }}'
    state: stopped
    enabled: false
  tags: cartridge-replicasets

- name: Delete instance files
  file:
    path: '{{ filepath }}'
    state: absent
  with_items:
    - '{{ instance_conf_file }}'
    - '{{ instance_control_sock }}'
    - '{{ instance_work_dir }}'
  loop_control:
    loop_var: filepath
  tags: cartridge-replicasets
