---

- when: cartridge_failover is not none or cartridge_failover_params is not none
  tags: cartridge-config
  block:
    - import_tasks: 'blocks/set_control_instance.yml'
      when: not control_instance

    - name: 'Configure failover'
      cartridge_configure_failover:
        failover_params: '{{ cartridge_failover_params | default(cartridge_failover) }}'
        console_sock: '{{ control_instance.console_sock }}'
      run_once: true
      delegate_to: '{{ control_instance.name }}'
