---

- when: not expelled
  tags: cartridge-instances
  block:
    - name: 'Manage instance parameters in runtime'
      cartridge_instance:
        console_sock: '{{ instance_info.console_sock }}'
        config: '{{ config }}'
        cartridge_defaults: '{{ cartridge_defaults }}'
      when: >-
        not restarted and not expelled

    - name: 'Check if instance restart is forced or required to apply changes'
      cartridge_set_needs_restart:
        restarted: '{{ restarted }}'
        app_name: '{{ cartridge_app_name }}'
        config: '{{ config }}'
        cartridge_defaults: '{{ cartridge_defaults }}'
        cluster_cookie: '{{ cartridge_cluster_cookie }}'
        stateboard: '{{ stateboard }}'
        instance_info: '{{ instance_info}}'

    - name: 'Place default config'
      copy:
        content: >-
          {{
            { cartridge_app_name: cartridge_defaults | combine({"cluster_cookie": cartridge_cluster_cookie}) }
            | to_nice_yaml
          }}
        dest: '{{ instance_info.app_conf_file }}'
        owner: tarantool
        group: tarantool
        mode: '644'
      when: not stateboard

    - name: 'Place instance config'
      copy:
        content: >-
          {{
            { instance_info.conf_section: config }
              | to_nice_yaml
          }}
        dest: '{{ instance_info.conf_file }}'
        owner: tarantool
        group: tarantool
        mode: '644'
