---
- name: Deploy my Tarantool Cartridge app
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Import Tarantool Cartridge role
      import_role:
        name: tarantool.cartridge
