---
name: Push rockspec

on:
  push:
    tags:
      - '*'

jobs:
  publish-role:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish role to Ansible Galaxy
        uses: robertdebock/galaxy-action@1.1.0
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
